/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;

import java.util.HashMap;
import java.util.Map;

public class Huffman {
    public static Map<Character, Integer> countFrequencies(String s){
         Map<Character, Integer> frequencies = new HashMap<>(); 

         for(int i = 0; i < s.length(); i++){ 
            frequencies.put(s.charAt(i), frequencies.getOrDefault(s.charAt(i), 0) + 1); 
         }

         return frequencies; 
    }

    public static void main(String[] args) {
       System.out.println(countFrequencies("Hello"));
    }
}
